### PR TITLE
Fix crash when key columns are deleted from a Frame

### LINKED ISSUE #2083: Segfault after removing a key column
```
import datatable as dt
DT = dt.Frame([[1], [2]])
DT.key = ["C0", "C1"]
del DT[0]
print(DT)
```

Produces `Segmentation fault: 11` / `Bus error: 10`.

### PR DESCRIPTION
**Pull request by st-pasha**
Closes #2083

### CODE REVIEW

**Comment by oleksiyskononenko** [comment]
Merging this to master as it passes all the tests, and this branch was already merged to #2085.

**Comment by oleksiyskononenko** [comment]
Btw, what about at least issuing a warning when we un-key frame deleting column(s)? We already do this when we de-duplicate column names during cbinding, in this case we also kind of doing operation that was not directly requested by the user.

**Comment by st-pasha** [comment]
Well, I was thinking that warnings ought to be reserved for the situations when something really unexpected happens. In this case a user deletes a column that is in the key -- pretty clear the key would no longer exist afterwards.

We could discuss further how to best judge the situations of when to issue warnings or not.

**Comment by oleksiyskononenko** [comment]
I guess it could be clear for us, but user didn't request this operation explicitly.

**Pull request merged**
