### PR TITLE
[ENH] create `max` method

### PR DESCRIPTION
**Pull request by samukweku**
WIP #2946
This creates a `max` method of `FExpr`, equivalent to `dt.max()`

### CODE REVIEW

**Review by oleksiyskononenko — COMMENTED** [review]
@samukweku It feels like your editor made a lot of automatic formatting changes: indenting, additional spaces, etc. The PR would be cleaner if we could revert all these changes that are not relevant to the new `.max` method.

**Comment by samukweku** [comment]
I am not sure what is wrong with my setup.  I'll start afresh

**Comment by oleksiyskononenko** [comment]
@samukweku you can revert formatting changes on the same branch and PR, just do `git checkout main -- file_that_got_accidentally_formatted` to get a fresh copy from `main` branch for the files that got formatted by the editor.

**Comment by samukweku** [comment]
@oleksiyskononenko , I started a fresh PR. I have to be extra careful now with the editor. :)

**Pull request closed without merging**
