### PR TITLE
Handle multi-params in function 'Parameters' section

### PR DESCRIPTION
**Pull request by st-pasha**
This PR allows to declare multiple parameters at once in the "parameters" section of documentation, e.g.
```
Parameters
----------
x, y, z: float
    (description of parameters)
```

WIP for #2605

### CODE REVIEW

**Comment by oleksiyskononenko** [comment]
What about making the grey color that is used for `,` and parameter type a little bit darker? Or at least the `,` to use the same style as the parameter type?

Screen Shot 2020-09-15 at 11 21 23 AM

**Comment by st-pasha** [comment]
Right now it is the same color as the separator `|` between types on the RHS. I agree that it looks kinda weird, but not sure whether it's the problem with the color, or maybe we need to do something else.

But I'd say it's a minor issue that we can address after the release.

**Comment by oleksiyskononenko** [comment]
Yeah, if the reason is not obvious it is, of course, not a high priority issue...

**Review by oleksiyskononenko — APPROVED** [review]

**Comment by oleksiyskononenko** [comment]
May be we can just use the blue background for the whole `x, y` stuff in this case. Will probably look way better than `x`, `y`.

**Pull request merged**
