### PR TITLE
Add comparison operators for strings (<, >, <=, >=)

### PR DESCRIPTION
**Pull request by bboe**
This pull request addresses some of the `String operations` tasks in #290.

### CODE REVIEW

**Comment by bboe** [comment]
@st-pasha any thoughts here?

**Comment by st-pasha** [comment]
@bboe Looks solid, however, let me test it locally too.

**Comment by bboe** [comment]
Thanks for the review and merging. And thanks for the awesome tool. I am thoroughly impressed by how quickly it parses CSV files (it was the fastest tool I've tried), and now I can quickly perform simple date-string filtering (assuming timezones are normalized in the file).

**Comment by st-pasha** [comment]
@bboe And thank **you** for contributing as well! 
Note that for the next version we've planned further improvements to CSV parser, string functions, and even dedicated date-time column type: see the roadmap at #2281. So I hope that you will have even more reasons to like `datatable` in the future!

**Pull request merged**
