### PR TITLE
#1699 Enhancement of documentation

### PR DESCRIPTION
**Pull request by Viktor-Demin**
closes https://github.com/h2oai/datatable/issues/1699
1) Merged quick-start.rst and using datatable.rst. and last one was deleted to avoid confusing
2) added a lot of new examples which hardcoded as raw html until ipython directive is fixed
3) created tutorial.ipynb - same as quick-start.rst but it can be executed. Maybe we can share it with users to give them ability of fast start? if not it can be deleted. 
4) fixed link in readme previous one didn't lead to anything

### CODE REVIEW

**Comment by st-pasha** [comment]
(btw, I'm on vacation currently, so I'd be able to take a look at this PR only later this week)

**Comment by Cheburusska** [comment]
@st-pasha thank you for notification. Have a nice vacation =)

**Comment by Cheburusska** [comment]
@st-pasha could you please review this request if you returned from vacation?

**Comment by Cheburusska** [comment]
@st-pasha kind reminder.

**Comment by Cheburusska** [comment]
@st-pasha @oleksiyskononenko could you please tell me what is a standard process of contribution? Maybe I can do something to help with review? Or maybe there are some problems with my request which I should fix? Maybe there is something what blocks my requests?

**Comment by st-pasha** [comment]
The major change in this PR is to merge `using-datatable.rst` and `quick-start.rst`, however such merger is not actually desirable. These two docs serve a very distinct purpose: "quick-start" is supposed to be a very quick introduction into the capabilities of datatable, almost like a cheatsheet, with lots of code and few explanations. It could benefit from being made more succinct, more broad, and having more cross-references to other documents. On the other hand, "using-datatable" is supposed to be a more in-depth exposition, almost like a Wikipedia article. The contents of "using-datatable" may be even split across multiple pages, if a single page becomes too long.

It is also unnecessary to replace quotation marks with "smart quotes": typography is a good thing, but such replacements are already done by a plugin, so they are superfluous in code.

Lastly, a large portion of this PR is an ipynb example file. Examples are good, and we need them, but in this case the example is just a doc page converted into a Jupyter notebook, which is probably not what we want.

**Pull request closed without merging**
