### PR TITLE
add power specific jenkinsfile

### PR DESCRIPTION
**Pull request by CreatureDev**

### CODE REVIEW

**Comment by CreatureDev** [comment]
Looks good

**Comment by CreatureDev** [comment]
closing to test s3 upload

**Comment by mmalohlava** [comment]
@CreatureDev Why another Jenkinsfile?  it should be in original one (Jenkinsfile).  The Jenkisfile2 contains PPC build but it was disabled because it was blocking development between Pasha and Arno.

**Comment by CreatureDev** [comment]
@mmalohlava Pasha wanted a separate build for ppc because it took too long for PRs to run through the ppc build
The time it took to build on ppc was inconsistent due to issue connecting to the machine and the build time simply being significantly longer if python dependencies changed
That is why it was commented out

**Pull request closed without merging**
