### PR TITLE
Allow frame to carry meta information

### PR DESCRIPTION
**Pull request by oleksiyskononenko**
In this PR we add a new frame `.meta` property that could be used by datatable functions/methods or by the user to store any frame relevant meta information.

WIP for https://github.com/h2oai/datatable/issues/2358
Closes https://github.com/h2oai/datatable/issues/2729

### CODE REVIEW

**Comment by st-pasha** [comment]
Should  `.meta` be  copied when doing `Frame.copy()`? Should it be preserved when saving  to Jay?

**Comment by oleksiyskononenko** [comment]
That's a good question, right now this is what I put in the docs

```
it is not guaranteed that the existing meta information will be preserved
by the functions and methods called on the frame
```

I guess we can gradually start handling it in the functions/methods where we believe it is necessary. We may want to be consistent with how we handle the `.source` for example. Do we keep it now when making a copy / saving to jay?

**Comment by st-pasha** [comment]
`.source` is preserved in `copy()`, but not in Jay, because the jay file becomes the new source.

**Comment by st-pasha** [comment]
Maybe we should clarify  this moment in the docs: "The meta information is not preserved when saving the data into a Jay file. This behavior may change in the future".

Because I think there could be an expectation that this information will be stored (for example Arrow format stores any meta information).

**Comment by oleksiyskononenko** [comment]
Yes, it is definitely a good idea to pickle/save to jay all the meta data related to a particular frame, but we need to think it through properly. For the moment I've improved the docs incorporating the changes you propose.

**Review by st-pasha — APPROVED** [review]

**Comment by oleksiyskononenko** [comment]
Travis seems to be slow, but all the tests are passed, so merging.

**Pull request merged**
