### PR TITLE
Pypi pipeline

### PR DESCRIPTION
**Pull request by semmjon**
It would be great if new versions were automatically pushed into the pypi repository.
Currently, I get installation errors (from pypi) and therefore always have to install from github.
Here is an example how to do github-actions to push releases to pypi (macos/windows/manylinux).

### CODE REVIEW

**Comment by oleksiyskononenko** [comment]
Thanks for your PR. We are currently working towards the new datatable version `1.1.0`, but before pushing release to pypi we have to complete all the tasks needed for that version: https://github.com/h2oai/datatable/issues/3046

Meanwhile, with every datatable fix/enhancement/new feature/etc. we're building dev wheels for macOS/linux/Windows and publish them in our S3 repo and AppVeyor, see https://datatable.readthedocs.io/en/latest/start/install.html#install-latest-dev-version for more details.

1) In this context, could you please clarify your suggestion?
2) Also, what are the errors you are getting when installing datatable from pypi?

**Comment by samukweku** [comment]
@semmjon is there an existing issue for this?

**Comment by semmjon** [comment]
There aren't any direct issues for this, though some are likely related to it. e.g. this https://github.com/h2oai/datatable/issues/3268

**Comment by semmjon** [comment]
The merge request is not quite enough. You still have to add the pypi token to the Project Secrets and possibly a Github token (if the release-draft action is to be used).

**Comment by semmjon** [comment]
@oleksiyskononenko I understand your concern. Possibly a pull request was the wrong approach here.
The error I get when installing has to do with "gendoc" and is no longer a problem in the current master.
I just wanted to give an example of a pipeline instead. :)
I've been waiting for a more up-to-date version in pypi for a relatively long time, which is why one possibility would be to work with smaller releases (continues integration).

**Comment by oleksiyskononenko** [comment]
@semmjon Yes, I see what you mean. Can you just install datatable from our S3 repo? The wheels we are producing now are the dev wheels, so they shouldn’t be directly published to PyPi for the moment.

**Comment by semmjon** [comment]
Yes, no problem. I just created my own Pypi project, where I can already push previous releases. 
I'll use my own project (repo) first. If you do the next release I might switch again.
The pull request can be closed :)

**Pull request closed without merging**
