### PR TITLE
New theme for documentation

### PR DESCRIPTION
**Pull request by st-pasha**
Trying to create a new theme for documentation, which would provide a cleaner and more modern look.

### CODE REVIEW

**Comment by oleksiyskononenko** [comment]
The "Table of Contents" menu seems to be buggy. When I click an item there it shows me that item, but on the menu it selects the previous one.

**Comment by oleksiyskononenko** [comment]
In some case when I click on the item on the left, the right menu jumps to the last item immediately:
Screen Shot 2020-10-20 at 4 16 21 PM

**Comment by oleksiyskononenko** [comment]
Submodule functions, like for math or models submodules, are rendered again black for some reason and are not clickable anymore:

Screen Shot 2020-10-20 at 4 18 20 PM

**Comment by st-pasha** [comment]
Re 1: fixed
Re 2: the side menu shows current section based on the scroll position of the page. If the sections are too short so that all of them are on the same page, then there is no really wrong answer here.

**Comment by oleksiyskononenko** [comment]
Re 2: Yes, but it is more intuitive to show the first section that is available on the page rather than the last one.

**Comment by oleksiyskononenko** [comment]
Btw, the module link is still broken and black:

Screen Shot 2020-10-26 at 11 38 33 AM

**Comment by oleksiyskononenko** [comment]
Also, I'm not sure if this is only my local problem, but the `csv-table` is not rendered well in the new theme:

Screen Shot 2020-10-26 at 1 00 54 PM

**Comment by st-pasha** [comment]
> Btw, the module link is still broken and black:

This is broken in our current documentation too, so not related to this PR.

> csv-table is not rendered well in the new theme:

Indeed, the styles for csv table are missing. However, we already have an issue to fix styling of these "syntax comparison" pages (#2625), so we can consider this problem as part of that issue.

**Comment by oleksiyskononenko** [comment]
>This is broken in our current documentation too, so not related to this PR.

Yes, I thought it was `1.1` that you said was fixed.

**Pull request merged**
