### PR TITLE
Docs style small fixes

### PR DESCRIPTION
**Pull request by RaffaeleMorganti**
I think these small modification can improve doc usability

- Added a small scrollbar in the left menu

old | new
---|---
|

- Index styles modified to prevent elements overlay

old | new
---|---
|

### CODE REVIEW

**Comment by pradkrish** [comment]
I like the introduction of scroll bar.  The overlay does happen sometimes when I resize the window but sometimes it doesn't. It seems to be inconsistent. is that part of this PR? (sorry, I have no knowledge of html and css, that's why I am asking).

**Comment by RaffaeleMorganti** [comment]
For the scrollbar is simply css (actually is behind the page main content so it's hidden), I simply moved it 10px on left to let it be visible.

In the index page actually there are
* logo and badges aligned to keep a fixed distance to the right of the page
*  buttons menu aligned to keep a fixed distance to the left of the page

This cause them to overlay with certain window sizes

With the modification:
* logo and badges are positioned inline with text, no more with absolute position, so they cannot overlay anything (if window is too small they are shown into multiple lines)
* buttons menu is aligned to stay centered in the page

This make overlays impossible on any window size

Hope this clarify

**Comment by pradkrish** [comment]
yeah, it does. I will let others with web design knowledge decide.

**Comment by oleksiyskononenko** [comment]
@RaffaeleMorganti have you seen this PR https://github.com/h2oai/datatable/pull/2696 ? The new theme seems to already have a scroll bar at the left:

Screen Shot 2020-10-26 at 11 19 28 AM

**Comment by RaffaeleMorganti** [comment]
@oleksiyskononenko oh I didn't know that. The version I pulled is simply the one I use as local reference. 
Nice to see the new theme, it looks pretty good, so I close this PR.

Since I looked at the new theme, please notice that in my opinion the lack of screen responsivity make it actually not really comfortable to use when not in full screen mode.

**Comment by st-pasha** [comment]
Thanks for your feedback, Raffaele. I've tried to make some style adjustments to make it look better at small screen widths. Still, there may be some room for improvement there, so suggestions/PRs welcome!

**Pull request closed without merging**
