### PR TITLE
Update docs and release notes wrt Windows support 

### LINKED ISSUE #1114: Support datatable on Windows
How about Windows support? Win7 & Win10

### PR DESCRIPTION
**Pull request by oleksiyskononenko**
With the new release datatable will also be available on Windows. In this PR we update documentation and release notes accordingly.

Closes #1114

### CODE REVIEW

**Comment by angela0xdata** [comment]
@oleksiyskononenko I think you need to keep the proper product name => Mac OS X. 
Or is there a specific reason why that was changed?

**Comment by oleksiyskononenko** [comment]
@angela0xdata It seems that the proper product name has changed, now it is `macOS` and not `Mac OS X`: https://en.wikipedia.org/wiki/MacOS The last four versions bear this name https://en.wikipedia.org/wiki/MacOS_version_history#Releases and it is also `macOS` on the official Apple website https://www.apple.com/macos/catalina/

**Comment by angela0xdata** [comment]
😱 Wow! Thanks so much for the info!

**Comment by oleksiyskononenko** [comment]
@angela0xdata You're welcome, thanks for the review.

**Pull request merged**
